name: Continuous Integration
on: [ push, pull_request ]

env:
  E2E_PACKAGE_PATH: internal/controller
  GINKGO_PACKAGE_NAME: github.com/onsi/ginkgo/v2/ginkgo

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest
    env:
      TEST_AZP_POOL_NAME: "automated-testing"
      TEST_EXPECTED_AZP_POOL_ID: "12"
      TEST_AZP_ORGANIZATION_URL: ${{ secrets.AZP_ORGANIZATION_URL }}
      TEST_AZP_TOKEN: ${{ secrets.AZP_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.3"
          install-go: false

      - name: Run tests
        run: |
          go install $GINKGO_PACKAGE_NAME
          ginkgo --skip-package $E2E_PACKAGE_PATH -r

  end-to-end-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind-node-image:
          - "kindest/node:v1.27.10"
          - "kindest/node:v1.28.6"
          - "kindest/node:v1.29.1"
    steps:
      - uses: actions/checkout@v4

      - name: download and install ktunnel
        run: |
          curl -L --silent -o ktunnel.deb https://github.com/omrikiei/ktunnel/releases/download/v1.6.1/ktunnel_1.6.1_linux_amd64.deb
          sudo dpkg -i ktunnel.deb

      - uses: azure/setup-helm@v4
        with:
          version: 'latest' # default is latest (stable)
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Build Docker images without pushing
        run: ./build-docker-images.sh

      - name: Run tests
        env:
          KIND_NODE_IMAGE: ${{ matrix.kind-node-image }}
        run: |
          go install $GINKGO_PACKAGE_NAME
          ginkgo $E2E_PACKAGE_PATH
